In [1]:
#Importing csv into python as a dataset
import numpy as np
import pandas as pd
dataset = pd.read_csv(r'C:\Users\Aniruddh\Desktop\mortgage-classifier-master\utils\loan_mortgage_data.csv')

In [2]:
#replacing false with 0 and true with 1
dataset.co_applicant = dataset.co_applicant.replace({True: 1, False: 0})

In [3]:
#Filling empty values with mean
dataset=dataset.fillna(dataset.mean())

In [4]:
#Converting into numpy array
dataset.to_numpy

<bound method DataFrame.to_numpy of         row_id  loan_type  property_type  loan_purpose  occupancy  \
0            0          3              1             1          1
1            1          1              1             3          1
2            2          2              1             3          1
3            3          1              1             1          1
4            4          1              1             1          1
...        ...        ...            ...           ...        ...
499995  499995          1              1             1          2
499996  499996          1              1             1          1
499997  499997          1              2             1          1
499998  499998          1              1             2          1
499999  499999          1              1             3          1

        loan_amount  preapproval  msa_md  state_code  county_code  ...  \
0                70            3      18          37          246  ...
1               178            3     369          52          299  ...
2               163            3      16          10          306  ...
3               155            1     305          47          180  ...
4               305            3      24          37           20  ...
...             ...          ...     ...         ...          ...  ...
499995          150            1      -1          -1           -1  ...
499996          140            3      74          47           98  ...
499997           22            3      -1          46          131  ...
499998           35            3     367           6          149  ...
499999           71            3     408          28          133  ...

        applicant_income   population  minority_population_pct  \
0                   24.0  6203.000000                 44.23000
1                   57.0  5774.000000                 15.90500
2                   67.0  6094.000000                 61.27000
3                  105.0  6667.000000                  6.24600
4                   71.0  6732.000000                100.00000
...                  ...          ...                      ...
499995              87.0  5416.833956                 31.61731
499996             216.0  3452.000000                  6.88700
499997              35.0  2925.000000                 36.04600
499998              41.0  3442.000000                 98.87900
499999              85.0  3856.000000                 12.09500

        ffiecmedian_family_income  tract_to_msa_md_income_pct  \
0                    60588.000000                   50.933000
1                    54821.000000                  100.000000
2                    67719.000000                  100.000000
3                    78439.000000                  100.000000
4                    63075.000000                   82.200000
...                           ...                         ...
499995               69235.603298                   91.832624
499996               86307.000000                  100.000000
499997               47826.000000                  100.000000
499998               60327.000000                   62.803000
499999               45033.000000                  100.000000

        number_of_owner-occupied_units  number_of_1_to_4_family_units  lender  \
0                           716.000000                    2642.000000    4536
1                          1622.000000                    2108.000000    2458
2                           760.000000                    1048.000000    5710
3                          2025.000000                    2299.000000    5888
4                          1464.000000                    1847.000000     289
...                                ...                            ...     ...
499995                     1427.718282                    1886.147065     969
499996                     1423.000000                    1944.000000    5359
499997                     1062.000000                    1762.000000    2318
499998                      618.000000                    1297.000000    5339
499999                     1525.000000                    2750.000000    5710

        co_applicant  accepted
0                  0         1
1                  0         0
2                  0         1
3                  1         1
4                  0         1
...              ...       ...
499995             1         0
499996             1         0
499997             0         0
499998             0         0
499999             1         0

[500000 rows x 23 columns]>

In [5]:
#Scaling or Normalizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(dataset)

array([[-1.73204734,  2.36581379, -0.20591757, ...,  0.44381963,
        -0.81658504,  0.9995441 ],
       [-1.73204042, -0.53040833, -0.20591757, ..., -0.68656561,
        -0.81658504, -1.0004561 ],
       [-1.73203349,  0.91770273, -0.20591757, ...,  1.08244921,
        -0.81658504,  0.9995441 ],
       ...,
       [ 1.73203349, -0.53040833,  4.11554237, ..., -0.76272246,
        -0.81658504, -1.0004561 ],
       [ 1.73204042, -0.53040833, -0.20591757, ...,  0.88063356,
        -0.81658504, -1.0004561 ],
       [ 1.73204734, -0.53040833, -0.20591757, ...,  1.08244921,
         1.2246122 , -1.0004561 ]])

In [6]:
#Dropping unnecessary columns
dataset.drop(['applicant_sex','applicant_ethnicity','applicant_race','state_code','row_id','tract_to_msa_md_income_pct'],axis=1)

,loan_type,property_type,loan_purpose,occupancy,loan_amount,preapproval,msa_md,county_code,applicant_income,population,minority_population_pct,ffiecmedian_family_income,number_of_owner-occupied_units,number_of_1_to_4_family_units,lender,co_applicant,accepted
0,3,1,1,1,70,3,18,246,24.0,6203.000000,44.23000,60588.000000,716.000000,2642.000000,4536,0,1
1,1,1,3,1,178,3,369,299,57.0,5774.000000,15.90500,54821.000000,1622.000000,2108.000000,2458,0,0
2,2,1,3,1,163,3,16,306,67.0,6094.000000,61.27000,67719.000000,760.000000,1048.000000,5710,0,1
3,1,1,1,1,155,1,305,180,105.0,6667.000000,6.24600,78439.000000,2025.000000,2299.000000,5888,1,1
4,1,1,1,1,305,3,24,20,71.0,6732.000000,100.00000,63075.000000,1464.000000,1847.000000,289,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,1,1,1,2,150,1,-1,-1,87.0,5416.833956,31.61731,69235.603298,1427.718282,1886.147065,969,1,0
499996,1,1,1,1,140,3,74,98,216.0,3452.000000,6.88700,86307.000000,1423.000000,1944.000000,5359,1,0
499997,1,2,1,1,22,3,-1,131,35.0,2925.000000,36.04600,47826.000000,1062.000000,1762.000000,2318,0,0
499998,1,1,2,1,35,3,367,149,41.0,3442.000000,98.87900,60327.000000,618.000000,1297.000000,5339,0,0
499999,1,1,3,1,71,3,408,133,85.0,3856.000000,12.09500,45033.000000,1525.000000,2750.000000,5710,1,0

In [7]:
#Slicing the dataset
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
#Splitting the dataset into a training:testing split of 90:10
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10)

In [9]:
#Importing random forest classifier and training it
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=90,n_jobs=4,max_depth=17, random_state=0)
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=17, n_estimators=90, n_jobs=4, random_state=0)

In [10]:
#predicting loan approval for test cases
y_pred = clf.predict(X_test)

In [11]:
#Checking accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[15901  9061]
 [ 6296 18742]]
Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.64      0.67     24962
           1       0.67      0.75      0.71     25038

    accuracy                           0.69     50000
   macro avg       0.70      0.69      0.69     50000
weighted avg       0.70      0.69      0.69     50000

Accuracy: 0.69286

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.metrics import roc_curve, roc_auc_score,plot_confusion_matrix

In [16]:
plot_confusion_matrix(clf, X_test, y_test,normalize='true')
plt.show()

ImportError: plot_confusion_matrix requires matplotlib. You can install matplotlib with `pip install matplotlib`